
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suda-official-website
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
