services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
    restart: always
    container_name: suda-official-website
    networks:
      - suda-network

networks:
  suda-network:
    driver: bridge 
